spring:
  application:
    name: encrypt-file
  config:
    import:
      - optional:file:.env[.properties]
  
  # Profile 설정
  profiles:
    active: local
  
  # JPA 설정 (공통)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

# 암호화된 설정 값들 (예제)
demo:
  database:
    url: ENC(yCqDko4fL0mQljG8KS8Gey2s5mr71gAtEwy7cJkgOlUeYWicns72doJ1LEPmtCs+GSXLaW4bLFM0vgza0TCKCQH3IH1ax1X+tK8fUo+Jqqs=)
    username: ENC(hQ7i5WXfbqWM2FuVL7f4geBb7+hOe4jYosFYR/Md/7vwOj1WQsvABsibY2gm9cGa)
    password: ENC(Chpl+SCx9F8XdzuonfmPB2zpz3QORdG5465T+/vLECbwP4OT1dPlFjdAlNiq/xSy)

# 로깅 설정
logging:
  level:
    root: INFO
    com.github.ulisesbocchio.jasyptspringboot: DEBUG
    org.jasypt: DEBUG
    demo.encryptfile: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
