server:
  port: 9999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NtoZero/config_practice
          default-label: config_practice
          clone-on-start: true
          timeout: 10
          search-paths: config-file
        health:
          repositories:
            config-repo:
              label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: INFO
