spring:
  application:
    name: encrypt-file
  config:
    import:
      - optional:file:.env[.properties]
  
  # Profile 설정
  profiles:
    active: local
  
  # JASYPT 설정 (공통)
  jasypt:
    encryptor:
      algorithm: PBEWITHHMACSHA512ANDAES_256
      key-obtention-iterations: 100000
      pool-size: 2
      key-store:
        location: ${KEYSTORE_LOCATION:file:secrets/keystore.p12}
        password: ${JASYPT_STOREPASS}
        alias: jasypt-secret-key
  
  # JPA 설정 (공통)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

# 암호화된 설정 값들 (예제)
demo:
  database:
    url: ENC(oPgMpzmsx6ZoCsdJvf5uUuqyAoFatextiDYRZjmHFF9FGTdzuHY7hXQGeS6hIJRClEfJfqd45RhBEYXZK2TteRLcD7gWJo8pAE6OIpCKTZY=)
    username: ENC(/f+4vIgAaxDpjqpLY2/yhhCZHIZ6xHZeCd+2yb138a4EcZC8MN6OW1SWPM6S2ic9)
    password: ENC(Erg8AnnoW14aNvMAnS6PevTNmGON+PT6Fpf7//013MqRGcPnYB3Zmdyn9ywEboy9)
  api:
    key: ENC(encrypted-api-key-here)
    secret: ENC(encrypted-secret-here)

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 로깅 설정
logging:
  level:
    root: INFO
    com.github.ulisesbocchio.jasyptspringboot: DEBUG
    org.jasypt: DEBUG
    demo.encryptfile: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
