spring:
  # 운영 환경 설정
  jasypt:
    encryptor:
      key-store:
        location: ${KEYSTORE_LOCATION:file:/etc/secrets/keystore.p12}
  
  # MySQL 데이터베이스 설정 (암호화된 값 사용)
  datasource:
    url: ${demo.database.url}
    username: ${demo.database.username}
    password: ${demo.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 설정 (운영)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

# Actuator 설정 (운영)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# 운영 환경 로깅
logging:
  level:
    root: WARN
    demo.encryptfile: INFO
    com.github.ulisesbocchio.jasyptspringboot: WARN
    org.jasypt: WARN
  file:
    name: /var/log/encrypt-file/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB
