server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.example: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info