# Keystore Property Source Demo Configuration
spring:
  application:
    name: encloader-demo
  
  # Jasypt 설정 예시 - keystore의 JASYPT_PASSWORD 값으로 치환됨
  jasypt:
    encryptor:
      password: ${JASYPT_PASSWORD:default-password}
      algorithm: PBEWithMD5AndDES
      key-obtention-iterations: 1000
      pool-size: 1
      provider-name: SunJCE
      salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
      string-output-type: base64

# Keystore 설정
keystore:
  path: ${KEYSTORE_LOCATION:file:encloader/scripts/secrets/keystore.p12}
  password: ${KEYSTORE_PASSWORD:}

# 로깅 설정
logging:
  level:
    com.example.keystore: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 데모용 설정들
demo:
  encrypted-value: ${DEMO_SECRET:not-found}
  database-password: ${DB_PASSWORD:default-db-password}
  api-key: ${API_KEY:default-api-key}
